export interface Ocorrencia {
  codigo: number;
  descricao: string;
  situacao: string;
}

// Mapeamento extraído de Tipos_ocorrencias_1786730814584.csv
export const OCORRENCIAS: Record<number, Ocorrencia> = {
  10166: { codigo: 10166, descricao: "ABONO HORARIO DE CORTE", situacao: "PENDENCIA CLIENTE" },
  10199: { codigo: 10199, descricao: "ABONO PRAZO AUTORIZADO CLIENTE", situacao: "NENHUM" },
  10129: { codigo: 10129, descricao: "AGUARDANDO AUTORIZACAO CARRO DEDICADO", situacao: "PENDENCIA CLIENTE" },
  93: { codigo: 93, descricao: "AGUARDANDO CARTA DE CORRECAO", situacao: "PENDENCIA CLIENTE" },
  10103: { codigo: 10103, descricao: "AGUARDANDO DATA DO AGENDAMENTO", situacao: "PENDENCIA CLIENTE" },
  85: { codigo: 85, descricao: "APREENSAO FISCAL DA MERCADORIA", situacao: "PENDENCIA CLIENTE" },
  10198: { codigo: 10198, descricao: "ATRASO NA DISTRIBUICAO - FILIAL DE ENTREGA", situacao: "NENHUM" },
  10177: { codigo: 10177, descricao: "AVARIA NA EMBALAGEM", situacao: "PENDENCIAS SOLUCOES OPERACIONAIS" },
  79: { codigo: 79, descricao: "AVARIA PARCIAL", situacao: "PENDENCIAS SOLUCOES OPERACIONAIS" },
  78: { codigo: 78, descricao: "AVARIA TOTAL", situacao: "PENDENCIAS SOLUCOES OPERACIONAIS" },
  10169: { codigo: 10169, descricao: "BOTICARIO - FRANQUIA ABRIU DEVOLUCAO PARA OUTRA TRANSPORTADO", situacao: "PENDENCIA" },
  10167: { codigo: 10167, descricao: "BOTICARIO - FRANQUIA NAO ESTAVA COM VOLUME PRONTO", situacao: "PENDENCIA" },
  91: { codigo: 91, descricao: "BOTICARIO - ENTREGA PROGRAMADA", situacao: "PENDENCIA" },
  10174: { codigo: 10174, descricao: "BOTICARIO - FRANQUIA NAO TINHA CONHECIMENTO DA COLETA", situacao: "PENDENCIA" },
  10165: { codigo: 10165, descricao: "BOTICARIO - FRANQUIA NAO ESTAVA COM A NOTA FISCAL PRONTA", situacao: "PENDENCIA" },
  10209: { codigo: 10209, descricao: "BOTICARIO - COLETA REALIZADA", situacao: "FINALIZADA" },
  209: { codigo: 209, descricao: "CHEGADA ATRASADA", situacao: "NENHUM" },
  10175: { codigo: 10175, descricao: "CHEGADA NA CIDADE OU FILIAL DE DESTINO", situacao: "NENHUM" },
  276: { codigo: 276, descricao: "CLIENTE - COLETA NAO REALIZADA", situacao: "PENDENCIA" },
  77: { codigo: 77, descricao: "CLIENTE DESTINO MUDOU DE ENDERECO", situacao: "PENDENCIA CLIENTE" },
  29: { codigo: 29, descricao: "CLIENTE RETIRA MERCADORIA", situacao: "PENDENCIA CLIENTE" },
  10140: { codigo: 10140, descricao: "CLIENTE SEM VERBA PARA PAGAR O FRETE", situacao: "PENDENCIA CLIENTE" },
  10172: { codigo: 10172, descricao: "CLIENTE SEM GRADE DE AGENDAMENTO", situacao: "PENDENCIA CLIENTE" },
  10180: { codigo: 10180, descricao: "COLETA AUTOMATICA SEM MERCADORIA", situacao: "FINALIZADA" },
  10178: { codigo: 10178, descricao: "COLETA CANCELADA", situacao: "FINALIZADA" },
  147: { codigo: 147, descricao: "COLETA REALIZADA NORMALMENTE", situacao: "FINALIZADA" },
  105: { codigo: 105, descricao: "COMPROVANTE DE ENTREGA - RECEBIDO", situacao: "NENHUM" },
  402: { codigo: 402, descricao: "COMPROVANTE ARQUIVADO", situacao: "NENHUM" },
  171: { codigo: 171, descricao: "COMPROVANTE RETIDO PELO DESTINATARIO", situacao: "PENDENCIA CLIENTE" },
  106: { codigo: 106, descricao: "COMPROVANTE REMOVIDO DA REMESSA", situacao: "PENDENCIA" },
  125: { codigo: 125, descricao: "CTE AUTORIZADO PELO SEFAZ", situacao: "GERAL" },
  126: { codigo: 126, descricao: "CTE CANCELADO / ANULADO", situacao: "FINALIZADA" },
  10187: { codigo: 10187, descricao: "CTE EM DUPLICIDADE", situacao: "FINALIZADA" },
  10189: { codigo: 10189, descricao: "CTE SUBSTITUIDO", situacao: "FINALIZADA" },
  21: { codigo: 21, descricao: "DESTINATARIO AUSENTE", situacao: "PENDENCIA CLIENTE" },
  10164: { codigo: 10164, descricao: "DEVOLUCAO AUTORIZADA PELO REMETENTE", situacao: "FINALIZADA" },
  10208: { codigo: 10208, descricao: "DIVERGENCIA DE LACRE", situacao: "NENHUM" },
  116: { codigo: 116, descricao: "EDI - ENVIADO AUTOMATICAMENTE", situacao: "NENHUM" },
  10157: { codigo: 10157, descricao: "EM ROTA DE ENTREGA", situacao: "TRANSITO" },
  10163: { codigo: 10163, descricao: "EM TRANSFERENCIA ENTRE FILIAIS DA TRANSPORTADORA", situacao: "PENDENCIA" },
  60: { codigo: 60, descricao: "EMISSAO ERRADA - OUTRA UNIDADE DE ENTREGA", situacao: "PENDENCIA" },
  123: { codigo: 123, descricao: "EMISSAO REALIZADA VIA EDI", situacao: "Emissao" },
  100: { codigo: 100, descricao: "EMISSAO REALIZADA", situacao: "GERAL" },
  113: { codigo: 113, descricao: "EMITIDO CTRC DO TRANSPORTADOR", situacao: "GERAL" },
  6: { codigo: 6, descricao: "ENDERECO NAO LOCALIZADO", situacao: "PENDENCIA CLIENTE" },
  10200: { codigo: 10200, descricao: "ENTREGA - DEVOLUCAO WURTH", situacao: "FINALIZADA" },
  20: { codigo: 20, descricao: "ENTREGA PREJUDICADA POR FALTA-HORARIO DE TEMPO HABIL", situacao: "PENDENCIA" },
  1: { codigo: 1, descricao: "ENTREGA REALIZADA NORMALMENTE", situacao: "FINALIZADA" },
  10206: { codigo: 10206, descricao: "ENTREGA REALIZADA MANUAL", situacao: "FINALIZADA" },
  10184: { codigo: 10184, descricao: "ENTREGA REALIZADA RODOVIASUL", situacao: "FINALIZADA" },
  170: { codigo: 170, descricao: "ENTREGA REALIZADA PARCIAL", situacao: "PENDENCIA" },
  76: { codigo: 76, descricao: "ESTRADA/ENTRADA DE ACESSO INTERDITADA", situacao: "TRANSITO" },
  10132: { codigo: 10132, descricao: "EXCESSO DE VEICULOS - FILA DE ESPERA", situacao: "PENDENCIA CLIENTE" },
  81: { codigo: 81, descricao: "EXTRAVIO PARCIAL", situacao: "PENDENCIAS SOLUCOES OPERACIONAIS" },
  80: { codigo: 80, descricao: "EXTRAVIO TOTAL", situacao: "PENDENCIAS SOLUCOES OPERACIONAIS" },
  10134: { codigo: 10134, descricao: "GREVE NACIONAL (GREVE GERAL)", situacao: "GERAL" },
  10205: { codigo: 10205, descricao: "INSTABILIDADE COLETOR DE DADOS (OBRIGATORIO N CHAMADO)", situacao: "NENHUM" },
  145: { codigo: 145, descricao: "LOCAL FECHADO", situacao: "PENDENCIA CLIENTE" },
  165: { codigo: 165, descricao: "MANIFESTADO DE ENTREGA", situacao: "TRANSITO" },
  401: { codigo: 401, descricao: "MANIFESTO FINALIZADO", situacao: "Emissao" },
  135: { codigo: 135, descricao: "MATERIAL RECUSADO PELO CLIENTE", situacao: "PENDENCIA CLIENTE" },
  25: { codigo: 25, descricao: "MERCADORIA DEVOLVIDA PARA ANALISE DO CLIENTE ORIGEM", situacao: "PENDENCIA" },
  109: { codigo: 109, descricao: "MERCADORIA DEVOLVIDA AO CLIENTE DE ORIGEM", situacao: "FINALIZADA" },
  10107: { codigo: 10107, descricao: "MERCADORIA LOCALIZADA", situacao: "NENHUM" },
  53: { codigo: 53, descricao: "MERCADORIA NAO FOI EMBARCADA, PERMANECENDO NA ORIGEM", situacao: "NENHUM" },
  10204: { codigo: 10204, descricao: "MERCADORIA NAO FOI EMBARCADA, PERMANECENDO NO TRANSBORDO", situacao: "NENHUM" },
  14: { codigo: 14, descricao: "MERCADORIA SINISTRADA / ROUBO", situacao: "PENDENCIAS SOLUCOES OPERACIONAIS" },
  18: { codigo: 18, descricao: "MERCADORIA TROCADA", situacao: "PENDENCIAS SOLUCOES OPERACIONAIS" },
  10191: { codigo: 10191, descricao: "MOTIVO - INFORMACAO ADICIONAL", situacao: "NENHUM" },
  10203: { codigo: 10203, descricao: "NAO EMBARCADO - WURTH", situacao: "PENDENCIA" },
  141: { codigo: 141, descricao: "NF AGUARDA AGENDAMENTO CLIENTE", situacao: "PENDENCIA CLIENTE" },
  10156: { codigo: 10156, descricao: "NF LIBERADA PELA FISCALIZACAO", situacao: "PENDENCIA CLIENTE" },
  10186: { codigo: 10186, descricao: "PROCESSO DE RESSARCIMENTO RECEBIDO MATRIZ", situacao: "FINALIZADA" },
  58: { codigo: 58, descricao: "QUEBRA DE VEICULO", situacao: "PENDENCIA" },
  10112: { codigo: 10112, descricao: "RECUSA POR FALTA DE PEDIDO DE COMPRA", situacao: "PENDENCIA CLIENTE" },
  403: { codigo: 403, descricao: "REMESSA REMOVIDA DO MANIFESTO", situacao: "Emissao" },
  10192: { codigo: 10192, descricao: "SAC-ATENDIMENTO AO CLIENTE", situacao: "NENHUM" },
  103: { codigo: 103, descricao: "SAIDA EFETIVA", situacao: "GERAL" },
  513: { codigo: 513, descricao: "SAIDA PARA ENTREGA", situacao: "PENDENCIA" },
  82: { codigo: 82, descricao: "SOBRA DE MERCADORIA", situacao: "PENDENCIAS SOLUCOES OPERACIONAIS" },
  150: { codigo: 150, descricao: "TELEFONE NAO CORRESPONDE AO CLIENTE", situacao: "PENDENCIA CLIENTE" },
  101: { codigo: 101, descricao: "TRANSFERENCIA ENTRE BASES INICIADA", situacao: "NENHUM" },
  174: { codigo: 174, descricao: "TRANSFERENCIA ENTRE BASES FINALIZADA", situacao: "PENDENCIA" },
  10201: { codigo: 10201, descricao: "TRANSFERIDO PARA A BIG EXPRESS", situacao: "PENDENCIA" },
  10207: { codigo: 10207, descricao: "TRANSFERIDO PARA O GRUPO G5", situacao: "TRANSITO" },
  10176: { codigo: 10176, descricao: "TRANSPORTADORA - COLETA NAO REALIZADA", situacao: "PENDENCIA" },
  439: { codigo: 439, descricao: "VOLUME LIDO EM MANIFESTO DIVERGENTE", situacao: "NENHUM" },
  279: { codigo: 279, descricao: "VOLUME RETIRADO DO CONSOLIDADOR", situacao: "NENHUM" },
};

export function getOcorrenciaDescricao(codigo: number): string {
  const oco = OCORRENCIAS[codigo];
  return oco ? oco.descricao : `Código ${codigo}`;
}
